name: "mfisher87.github.io"
channels:
  - "conda-forge"
  - "nodefaults"
platforms:
  - "linux-64"
dependencies:
  - python ~=3.11.0

  # Framework dependencies
  - quarto ~=1.4.550
  - jupyter ~=1.0.0


  # Self-dependencies (e.g. I've written code that uses these in a document)
  - matplotlib-base ~=3.7.0
  - cartopy ~=0.21.1
