project:
  type: "website"

website:
  title: "Matt Fisher"
  site-url: "https://mfisher87.github.io"
  repo-url: &repo-url "https://github.com/mfisher87/mfisher87.github.io"
  repo-subdir: "content"
  repo-actions: ["edit", "issue"]

  navbar:
    left:
      - text: "About"
        # file: "about/index.md"
        menu:
          - text: "About me"
            file: "about/index.md"
          - text: "My projects"
            href: "about/my-work/projects/index.md"
          - text: "My workshops"
            href: "about/my-work/workshops/index.md"
          - text: "My other roles"
            href: "about/my-work/other-roles/index.md"
          - text: "My talks"
            href: "about/my-work/talks/index.md"
          - text: "My awards"
            href: "about/my-work/awards/index.md"
          - text: "My maintenance work"
            href: "about/my-work/maintenance/index.md"

      - text: "Résumé"
        file: "resume.pdf"
        target: "_blank"

      - text: "Blog"
        file: "posts/index.md"

      - text: "More"
        menu:
          - text: "Cognitive load"
            file: "cognitive_load.md"
          - text: "My learning objectives"
            file: "learning_objectives.md"
          - text: "My communities"
            file: "communities.md"
          - text: "My other sites"
            file: "internal_links.md"
          - text: "External links / blogroll"
            file: "external_links.md"
          - text: "---"
          - text: "2024 garden"
            file: "garden/2024.md"
          - text: "Crows"
            file: "crows.md"
          - text: "LEDs"
            file: "leds.md"

    right:
      - icon: "envelope-fill"
        text: " "
        aria-label: "Contact"
        href: "contact.md"

      - icon: "github"
        aria-label: "GitHub"
        href: "https://github.com/mfisher87"


  sidebar:
    - title: "About"
      style: "docked"
      contents:
        - text: "👤 About me"
          href: "about/index.md"
        - text: "🛠️ My work"
          href: "about/my-work/index.md"
          # contents: "about/my-work/*/index.md"
          contents:
            - "about/my-work/projects/index.md"
            - "about/my-work/workshops/index.md"
            - "about/my-work/other-roles/index.md"
            - "about/my-work/talks/index.md"
            - "about/my-work/awards/index.md"
            - "about/my-work/maintenance/index.md"


  page-footer:
    left: "© Matt Fisher 2024"
    right: "Built with [Quarto](https://quarto.org/) ❤️"


format:
  html:
    theme:
      light: ["flatly", "styles.scss"]
      dark: ["darkly", "styles.scss"]
    # Turn on emoji shortcodes:
    # NOTE: Doesn't work in sidebar, nav or front-matter
    from: "markdown+emoji"

    toc: true


# Enable comments by default
# IMPORTANT: Set `comments: false` on pages like indexes!
# TODO: This config is duplicated mostly for blog posts, how to DRY?
comments:
  giscus:
    repo: "mfisher87/mfisher87.github.io"
    repo-id: "R_kgDOIyvIJQ"
    category: "Other pages"
    category-id: "DIC_kwDOIyvIJc4CcIIr"
    mapping: "pathname"
    reactions-enabled: true
    input-position: "top"
    # TODO: In Quarto 1.4, light/dark themes are supported
    # https://github.com/quarto-dev/quarto-cli/issues/4820
    # theme:
    #   light: "preferred_color_scheme"
    #   dark: "noborder_dark"
    theme: "light"
    language: "en"
    loading: "lazy"
